name: Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the tag'
        required: true

jobs:
  create-tag:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ github.event.inputs.version }}',
              sha: context.sha
            })
